on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.12.x

      - name: Checkout source branch for building Pages
        uses: actions/checkout@v1

      - name: Cache go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.OS }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-go-${{ env.cache-name }}-
            ${{ runner.OS }}-go-

      - name: Install dependencies
        run: |
          mkdir -p /tmp/gcy
          sudo apt-get install -y libgpgme-dev
          go mod download
          make test-deps
          if [[ ! -d /tmp/gcy/bats ]]; then
            git clone https://github.com/bats-core/bats-core.git /tmp/gcy/bats
            cd /tmp/gcy/bats
            ./install.sh /tmp/gcy
          fi

      - name: Lint
        run: make lint

      - name: Unit test
        run: REPORTS="/tmp/bc" make coverage

      - name: CLI test
        command: PATH="$PATH:/tmp/bc/bin" make integration-test

      - name: Push coverage results to Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-profile: /tmp/gcy/coverage.out
